palleta/cart/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from . import views

urlpatterns = [
    

    #cart:
    path('cart/', views.cart_view, name='cart'),
    path('add-to-cart/<int:variant_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update_quantity/', views.update_quantity, name='update_quantity'),

]

palleta/palleta/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
from django.conf import settings
from store.views import custom_404_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('store.urls')),
    path('', include('admin_panel.urls')),
    path('', include('userprofile.urls')),
    path('', include('userorder.urls')),
    path('', include('cart.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = custom_404_view

palleta/store/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from . import views
from store.views import custom_404_view

urlpatterns = [
    
    #home:
    path('',views.home ,name='home' ),

    # path('search/', views.search_view, name='search'),

    #category view:
    path('product-display/',views.product_page ,name='products-display' ),

    #product detail view:
    path('product-detail-view/<int:id>',views.product ,name='product-detail-view' ),

    
    #filter:
    path('products/filter/', views.product_filter, name='product_filter'),
    path('products/filters/', views.product_filters, name='product_filters'),
    
    #wishlist:
    path('wishlist/',views.wishlist,name="wishlist"),
    path('add_to_wishlistt/<int:variant_id>/', views.add_to_wishlistt, name='add_to_wishlistt'),
    path('remove_from_wishlist/<int:item_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),

    

    

    # URL pattern for the update_quantity view
    
    path('search/', views.search, name='search'),
    
    # URL for the autocomplete view
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    
    
    

]

palleta/store/models.py
from datetime import timedelta
from decimal import Decimal
from django.db import models
from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from userprofile.models import *
from django.utils import timezone
from multiselectfield import MultiSelectField



class Category(models.Model):
    name = models.CharField(max_length=100, null=False)
    image = models.ImageField(upload_to='category_images', null=True, blank=True)
    enabled = models.BooleanField(default=True) 
    # other fields...

    def __str__(self):
        return self.name
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ""
        return url


class Artist(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    

class Product(models.Model):
    name = models.CharField(max_length=100,unique=True)
    image = models.ImageField(upload_to='product_images', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, null=True, blank=True)
    # price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    # size = models.CharField(max_length=50, null=True, blank=True)
    medium = models.CharField(max_length=50, null=True, blank=True)
    style = models.CharField(max_length=50, null=True, blank=True)
    created_in = models.PositiveIntegerField(null=True, blank=True)
    seller = models.CharField(max_length=50, null=True, blank=True)
    enabled = models.BooleanField(default=True)
    
    

    # Add more fields as needed

    def __str__(self):
        return self.name




class Size(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class ProductVariant(models.Model):
    category =  models.ForeignKey(Category,on_delete=models.CASCADE,null=True, blank=True)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,null=True, blank=True)
    discount_percentage = models.PositiveIntegerField(null=True,blank=True)
    size = models.ForeignKey(Size,on_delete=models.CASCADE,null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_active = models.BooleanField(default=True)
    stock = models.PositiveIntegerField(default=0) 

    
    def __str__(self):
        return f"{self.product.name} - {self.size.name if self.size else 'No Size'} - ${self.price} - {'Active' if self.is_active else 'Inactive'}"
    
    @property
    def get_discount_price(self):

        Product_discount = self.discount_percentage if self.discount_percentage else 0
        discounted_price = Decimal(self.price)-Decimal(self.price) * (Decimal(Product_discount)/100)

        

        return round(discounted_price,0)

class Image(models.Model):
    variant = models.ForeignKey(ProductVariant, on_delete=models.CASCADE, related_name='images',null=True,blank=True)
    image = models.ImageField(upload_to='product_images')
    # Add any other relevant fields

    def __str__(self):
        return f"Image for {self.variant.product.name}"

class Coupon(models.Model):
    code = models.CharField(max_length=50, unique=True)
    discount = models.DecimalField(max_digits=8, decimal_places=2)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    minimum_order_amount = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    single_use_per_user = models.BooleanField(default=False)
    quantity = models.PositiveIntegerField(default=1)

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    coupon =  models.ForeignKey(Coupon,on_delete=models.CASCADE,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True, blank=True)

    def __str__(self):
        return f"Cart #{self.pk} for {self.user.username}"
    
    def get_total_price(self):
        return self.cartitem_set.aggregate(total_price=Sum('price'))['total_price']

    def get_discounted_total_price(self):
        total_price = self.get_total_price()
        if self.coupon:
            total_price -= self.coupon.discount
        return total_price
    # User = get_user_model()

@receiver(post_save, sender=User)
def create_cart(sender, instance, created, **kwargs):
    if created:
        Cart.objects.create(user=instance)
    


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    productvariant = models.ForeignKey(ProductVariant, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
        return f"{self.productvariant.product.name} ({self.quantity})"
    
    @property
    def subtotal(self):
        return self.quantity * self.price
    @property
    def item_price(self):
        return Decimal(self.quantity) * self.productvariant.price

    @property
    def get_discount_price(self):
        result = self.productvariant.get_discount_price
        discount_price  = self.productvariant.get_discount_price

        return Decimal(self.quantity) * Decimal(discount_price)


    
    def get_item_price(self):
        return Decimal(self.price) * Decimal(self.quantity)
   


class Order(models.Model):
    PAYMENT_STATUS_CHOICES = [
        ('PENDING','pending'),
        ('PAID','paid')]
    
    ORDER_STATUS_CHOICES =[
        ('CANCELLED', 'cancelled'),
        ('DELIVERED', 'Delivered'),
        ('SHIPPED', 'Shipped'),
        ('RETURNED', 'Returned'),
        ('ORDERED', 'Ordered'),
    ]
    PAYMENT_METHOD_CHOICES = [
        ('RAZORPAY', 'razorpay'),
        ('CASH_ON_DELIVERY', 'Cash on Delivery'),
        ('Wallet pay','Wallet pay')
    ]


    user = models.ForeignKey(User,on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.CASCADE,null=True, blank=True)
    payment_status = models.CharField(max_length=25, choices=PAYMENT_STATUS_CHOICES, default='pending')
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES,default='Cash on Delivery')
    order_status = models.CharField(max_length=20, choices=ORDER_STATUS_CHOICES, default='Ordered')
    message = models.TextField(null=True, blank=True)
    tracking_no = models.CharField(max_length=150,null=True ,blank=True)
    order_date = models.DateTimeField(default=timezone.now)
    delivery_date = models.DateTimeField(blank=True, null=True)
    applied_coupon = models.CharField(max_length=50, blank=True, null=True)
    razor_pay_order_id = models.CharField(max_length=150, null=True, blank=True)
    razor_pay_payment_id = models.CharField(max_length=150, null=True, blank=True)
    razor_pay_payment_signature = models.CharField(max_length=150, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_address = models.TextField()


    def __str__(self):
        return f"Order #{self.pk} for {self.user.username}"
    
    @property
    def return_period_expired(self):
        return_period_end_date = self.delivery_date + timezone.timedelta(days=5)
        return timezone.now() > return_period_end_date
    def _str_(self):
        return f"{self.id, self.tracking_no}", f"{self.id}  {self.user.username}"

    def save(self, *args, **kwargs):
        if not self.order_date:
            self.order_date = timezone.now()  # Set the order date to the current time if it's not set
        if not self.delivery_date:
            self.delivery_date = self.order_date + timedelta(hours=24)
        super().save(*args, **kwargs)


    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product_variant = models.ForeignKey(ProductVariant, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    @property
    def subtotal(self):
        return self.quantity * self.price

    def __str__(self):
        return f"{self.product_variant.product.name} ({self.quantity})"
    
    def get_item_price(self):
        return Decimal(self.price) * Decimal(self.quantity)


class Wishlist(models.Model):
     user = models.ForeignKey(User,on_delete=models.CASCADE)

     def __str__(self):
         return f"Wishlist for {self.user.username}"
     
class Wishlistitem(models.Model):
    wishlist = models.ForeignKey(Wishlist,on_delete=models.CASCADE)
    product = models.ForeignKey(ProductVariant,on_delete=models.CASCADE)

    def get_item_price(self):
        return self.product.price               
     

class Wallet(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def str(self):
        return f"{self.user.username}'s Wallet: {self.balance}"

@receiver(post_save, sender=User)
def create_wallet(sender, instance, created, **kwargs):
    if created:
        Wallet.objects.create(user=instance)

class WalletTransaction(models.Model):
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE, related_name='transactions')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE,blank=True, null=True)
    transaction_type = models.CharField(max_length=20, choices=(
        ('PURCHASE', 'Purchase'),
        ('CANCEL', 'Cancel'),
        ('RETURN', 'Return'),
    ))

    def _str_(self):

palleta/templates/store/product_page.html
{% extends 'store/base.html' %}
{% load static %}


		
{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
	
<style>
	/* Add custom styles here */
	.product-image {
	  height: 300px; /* Adjust the height as per your requirement */
	  object-fit: cover; /* This property ensures the image is proportionally scaled and covers the container */
	}
  </style>
  <style>
    /* Autocomplete dropdown style */
    .ui-autocomplete {
        max-height: 200px;
		max-width:180px;
        overflow-y: auto;
        overflow-x: hidden;
        z-index: 1000;
        border: 1px solid #e5e5e5;
        background-color: #fff;
    }

    .ui-menu-item {
        padding: 8px 12px;
        cursor: pointer;
    }

    .ui-state-hover,
    .ui-state-active {
        background-color: #f5f5f5;
    }
	.discount-badge {
		position: absolute;
		top: 10px;
		right: 10px;
		padding: 6px;
		background-color: red;
		color: white;
		border-radius: 5px;
		font-size: 12px;
		font-weight: bold;
		z-index: 1;
	  
	  }
</style>

	<!-- Product -->
	<div class="bg0 m-t-23 p-b-140">
		<div class="container">
			<div class="flex-w flex-sb-m p-b-52">
				<div class="flex-w flex-l-m filter-tope-group m-tb-10">
					<button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 how-active1" data-filter="*">
						All Products
					</button>
                    {% for category in categories %}
					<button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5" data-filter=".{{category.name}}">
						{{category.name}}
					</button>
                    {% endfor %}

					
				</div>     

				<form action="{% url 'search' %}" method="get" class="d-flex">
					<!-- Existing search feature -->
					<div class="flex-w flex-c-m m-tb-10">
						<div class="flex-c-m stext-106 cl6 size-104 bor4 pointer hov-btn3 trans-04 m-r-8 m-tb-4 js-show-filter">
							<i class="icon-filter cl2 m-r-6 fs-15 trans-04 zmdi zmdi-filter-list"></i>
							<i class="icon-close-filter cl2 m-r-6 fs-15 trans-04 zmdi zmdi-close dis-none"></i>
							Filter
						</div>
						<div class="flex-c-m stext-106 cl6 size-105 bor4 pointer hov-btn3 trans-04 m-tb-4 js-show-search">
							<i class="icon-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-search"></i>
							<i class="icon-close-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-close dis-none"></i>
							Search
						</div>
					</div>
								
					<!-- Search product -->
					<div class="dis-none panel-search w-full p-t-10 p-b-15">
						<div class="bor8 dis-flex p-l-15">
							<button class="size-113 flex-c-m fs-16 cl2 hov-cl1 trans-04" id="search-button">
								<i class="zmdi zmdi-search"></i>
							</button>
							<input class="mtext-107 cl2 size-114 plh2 p-r-15" type="text" name="query" placeholder="Search" id="searchInput">
						</div>
					</div>
				</form>
				
				

				<!-- Filter -->
				<div class="dis-none panel-filter w-full p-t-10">
					<div class="wrap-filter flex-w bg6 w-full p-lr-40 p-t-27 p-lr-15-sm">
						<div class="filter-col1 p-r-15 p-b-27">
							<div class="mtext-102 cl2 p-b-15">
								Sort By
							</div>

							<ul>
								<li class="p-b-6">
									<a href="{% url 'products-display' %}" class="filter-link stext-106 trans-04  {% if not request.GET.sort %} filter-link-active {% endif %}">
										Default
									</a>
								</li>

								<li class="p-b-6">
									<a href="?sort=popularity" class="filter-link stext-106 trans-04 {% if request.GET.sort == 'popularity' %} filter-link-active {% endif %}">
										Popularity
									</a>
								</li>

								{% comment %} <li class="p-b-6">
									<a href="#" class="filter-link stext-106 trans-04">
										Average rating
									</a>
								</li> {% endcomment %}

								<li class="p-b-6">
									<a href="?sort=newness" class="filter-link stext-106 trans-04 {% if request.GET.sort == 'newness' %} filter-link-active {% endif %}">
										Newness
									</a>
								</li>

								<li class="p-b-6">
									<a href="?sort=low_to_high" class="filter-link stext-106 trans-04 {% if request.GET.sort == 'low_to_high' %} filter-link-active {% endif %}">
										Price: Low to High
									</a>
								</li>
								<li class="p-b-6">
									<a href="?sort=high_to_low" class="filter-link stext-106 trans-04 {% if request.GET.sort == 'high_to_low' %} filter-link-active {% endif %}">
										Price: High to Low
									</a>
								</li>
							</ul>
						</div>

						<div class="filter-col2 p-r-15 p-b-27">
							<div class="mtext-102 cl2 p-b-15">
								Price
							</div>
						
							<ul>
								<li class="p-b-6">
									<a href="{% url 'product_filters' %}" class="filter-link stext-106 trans-04 {% if not request.GET.min_price and not request.GET.max_price %}filter-link-active{% endif %}">
										All
									</a>
								</li>
						
								<li class="p-b-6">
									<a href="{% url 'product_filters' %}?min_price=1000&max_price=2000" class="filter-link stext-106 trans-04 {% if request.GET.min_price == '1000' and request.GET.max_price == '2000' %}filter-link-active{% endif %}">
										$1000.00 - $2000.00
									</a>
								</li>
						
								<li class="p-b-6">
									<a href="{% url 'product_filters' %}?min_price=2000&max_price=5000" class="filter-link stext-106 trans-04 {% if request.GET.min_price == '2000' and request.GET.max_price == '5000' %}filter-link-active{% endif %}">
										$2000.00 - $5000.00
									</a>
								</li>
						
								<li class="p-b-6">
									<a href="{% url 'product_filters' %}?min_price=5000&max_price=10000" class="filter-link stext-106 trans-04 {% if request.GET.min_price == '5000' and request.GET.max_price == '10000' %}filter-link-active{% endif %}">
										$5000.00 - $10000.00
									</a>
								</li>
						
								{% comment %} <li class="p-b-6">
									<a href="{% url 'product_filter' %}?min_price=150&max_price=200" class="filter-link stext-106 trans-04 {% if request.GET.min_price == '150' and request.GET.max_price == '200' %}filter-link-active{% endif %}">
										$150.00 - $200.00
									</a>
								</li> {% endcomment %}
						
								<li class="p-b-6">
									<a href="{% url 'product_filters' %}?min_price=10000" class="filter-link stext-106 trans-04 {% if request.GET.min_price == '10000' %}filter-link-active{% endif %}">
										$10000.00+
									</a>
								</li>
							</ul>
						</div>

						

						{% comment %} <div class="filter-col4 p-b-27">
							<div class="mtext-102 cl2 p-b-15">
								Tags
							</div>

							<div class="flex-w p-t-4 m-r--5">
								<a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
									Fashion
								</a>

								<a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
									Lifestyle
								</a>

								<a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
									Denim
								</a>

								<a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
									Streetstyle
								</a>

								<a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
									Crafts
								</a>
							</div>
						</div> {% endcomment %}
					</div>
				</div>
			</div>

			<div class="row isotope-grid">
                {% for product in products %}
				{% if product.enabled == True %}
				<div class="col-6 col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item {{product.category}}">
					<!-- Block2 -->
					<div class="block2">
						<div class="block2-pic hov-img0">
							{% if product.productvariant_set.exists %}
								{% for variant in product.productvariant_set.all %}
									{% if variant.discount_percentage %}
									<div class="discount-badge">
										{{ variant.discount_percentage }}% Off
									</div>
									{% endif %}
								{% endfor %}
							{% endif %}
							<div class="variant-images">
								{% if product.productvariant_set.first.images.all %}
									<img class="product-image" src="{{ product.productvariant_set.first.images.first.image.url }}" alt="Product Variant Image" style="height: 25rem">
								{% else %}
									<p>No image available</p>
								{% endif %}
							</div>	

							<a href="{% url 'product-detail-view' product.id %}" class="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 show-modal1">
								view
							</a>
						</div>

						<div class="block2-txt flex-w flex-t p-t-14">
							<div class="block2-txt-child1 flex-col-l ">
								<a href="product-detail.html" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
									{{product.name}}
								</a>
								

								{% if product.productvariant_set.first.discount_percentage is not None %}
								<div class="d-flex">
									<span class="stext-105 cl2" style="text-decoration-line: line-through">
										₹ {{ product.productvariant_set.first.price }} 
									</span>
									<span class="stext-105 cl2 mx-3">
										₹ {{ product.discounted_price }} 
									</span>
								</div>
							{% else %}
								<span class="stext-105 cl3">
									₹ {{ product.productvariant_set.first.price }}	
								</span>
							{% endif %}
								
								
							</div>

							{% if product in product_in_wishlist %}
								<!-- Remove from Wishlist -->
								<a href="{% url 'remove_from_wishlist' product.id %}" class="wishlist-link">
									<button class="wishlist-button red">
										<i class="fas fa-heart"></i> <!-- Heart icon for Remove from Wishlist -->
									</button>
								</a>
							{% else %}
								<!-- Add to Wishlist -->
								<a href="{% url 'add_to_wishlistt' variant_id=product.id %}" class="wishlist-link">
									<button class="wishlist-button white">
										<i class="far fa-heart"></i> <!-- Empty heart icon for Add to Wishlist -->
									</button>
								</a>
							{% endif %}
						</div>
					</div>
				</div>
				{% endif %}
                {% endfor %}

				
			</div>

			<!-- Load more -->
			<div class="flex-c-m flex-w w-full p-t-45">
				<a href="#" class="flex-c-m stext-101 cl5 size-103 bg2 bor1 hov-btn1 p-lr-15 trans-04">
					Load More
				</a>
			</div>
		</div>
	</div>

	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
     <!-- <script src="https://kit.fontawesome.com/YOUR_KIT_CODE.js" crossorigin="anonymous"></script> -->
     
     <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
     <!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> -->
     
     
    
     <script>
        $("#searchInput").autocomplete({
    source: "{% url 'autocomplete' %}",
    open: function() {
        $(this).autocomplete('widget').css('width', $('#searchInput').width());
    }
});
     </script>
		
{%endblock%}